/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.languages.g2048.ui.internal.G2048Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class G2048ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(G2048Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		G2048Activator activator = G2048Activator.getInstance();
		return activator != null ? activator.getInjector(G2048Activator.UK_AC_KCL_INF_LANGUAGES_G2048_G2048) : null;
	}

}
