/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class G2048OutlineTreeProvider extends DefaultOutlineTreeProvider {

}
