/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.g2048;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Factory
 * @model kind="package"
 * @generated
 */
public interface G2048Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "g2048";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/languages/g2048/G2048";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "g2048";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  G2048Package eINSTANCE = uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048ProgramImpl
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getG2048Program()
   * @generated
   */
  int G2048_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int G2048_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int G2048_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.StatementImpl
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.TitleDefineStatementImpl <em>Title Define Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.TitleDefineStatementImpl
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getTitleDefineStatement()
   * @generated
   */
  int TITLE_DEFINE_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_DEFINE_STATEMENT__TITLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Title Define Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_DEFINE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.SizeDefineStatementImpl <em>Size Define Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.SizeDefineStatementImpl
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getSizeDefineStatement()
   * @generated
   */
  int SIZE_DEFINE_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_DEFINE_STATEMENT__SIZE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Size Define Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_DEFINE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.LevelDefineStatementImpl <em>Level Define Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.LevelDefineStatementImpl
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getLevelDefineStatement()
   * @generated
   */
  int LEVEL_DEFINE_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINE_STATEMENT__LEVEL = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINE_STATEMENT__ELEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Level Define Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_DEFINE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.Level <em>Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.g2048.g2048.Level
   * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getLevel()
   * @generated
   */
  int LEVEL = 5;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.g2048.g2048.G2048Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Program
   * @generated
   */
  EClass getG2048Program();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.g2048.g2048.G2048Program#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Program#getStatements()
   * @see #getG2048Program()
   * @generated
   */
  EReference getG2048Program_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.g2048.g2048.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement <em>Title Define Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title Define Statement</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement
   * @generated
   */
  EClass getTitleDefineStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement#getTitle()
   * @see #getTitleDefineStatement()
   * @generated
   */
  EAttribute getTitleDefineStatement_Title();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement <em>Size Define Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size Define Statement</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement
   * @generated
   */
  EClass getSizeDefineStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement#getSize()
   * @see #getSizeDefineStatement()
   * @generated
   */
  EAttribute getSizeDefineStatement_Size();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement <em>Level Define Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level Define Statement</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement
   * @generated
   */
  EClass getLevelDefineStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getLevel()
   * @see #getLevelDefineStatement()
   * @generated
   */
  EAttribute getLevelDefineStatement_Level();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getElement()
   * @see #getLevelDefineStatement()
   * @generated
   */
  EAttribute getLevelDefineStatement_Element();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.languages.g2048.g2048.Level <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Level</em>'.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.Level
   * @generated
   */
  EEnum getLevel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  G2048Factory getG2048Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048ProgramImpl
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getG2048Program()
     * @generated
     */
    EClass G2048_PROGRAM = eINSTANCE.getG2048Program();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference G2048_PROGRAM__STATEMENTS = eINSTANCE.getG2048Program_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.StatementImpl
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.TitleDefineStatementImpl <em>Title Define Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.TitleDefineStatementImpl
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getTitleDefineStatement()
     * @generated
     */
    EClass TITLE_DEFINE_STATEMENT = eINSTANCE.getTitleDefineStatement();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE_DEFINE_STATEMENT__TITLE = eINSTANCE.getTitleDefineStatement_Title();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.SizeDefineStatementImpl <em>Size Define Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.SizeDefineStatementImpl
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getSizeDefineStatement()
     * @generated
     */
    EClass SIZE_DEFINE_STATEMENT = eINSTANCE.getSizeDefineStatement();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_DEFINE_STATEMENT__SIZE = eINSTANCE.getSizeDefineStatement_Size();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.impl.LevelDefineStatementImpl <em>Level Define Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.LevelDefineStatementImpl
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getLevelDefineStatement()
     * @generated
     */
    EClass LEVEL_DEFINE_STATEMENT = eINSTANCE.getLevelDefineStatement();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL_DEFINE_STATEMENT__LEVEL = eINSTANCE.getLevelDefineStatement_Level();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL_DEFINE_STATEMENT__ELEMENT = eINSTANCE.getLevelDefineStatement_Element();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.g2048.g2048.Level <em>Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.g2048.g2048.Level
     * @see uk.ac.kcl.inf.languages.g2048.g2048.impl.G2048PackageImpl#getLevel()
     * @generated
     */
    EEnum LEVEL = eINSTANCE.getLevel();

  }

} //G2048Package
