/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.g2048;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Level</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getLevel()
 * @model
 * @generated
 */
public enum Level implements Enumerator
{
  /**
   * The '<em><b>One</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONE_VALUE
   * @generated
   * @ordered
   */
  ONE(0, "one", "one"),

  /**
   * The '<em><b>Two</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TWO_VALUE
   * @generated
   * @ordered
   */
  TWO(1, "two", "two"),

  /**
   * The '<em><b>Three</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THREE_VALUE
   * @generated
   * @ordered
   */
  THREE(2, "three", "three"),

  /**
   * The '<em><b>Four</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FOUR_VALUE
   * @generated
   * @ordered
   */
  FOUR(3, "four", "four"),

  /**
   * The '<em><b>Five</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIVE_VALUE
   * @generated
   * @ordered
   */
  FIVE(4, "five", "five"),

  /**
   * The '<em><b>Six</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIX_VALUE
   * @generated
   * @ordered
   */
  SIX(5, "six", "six"),

  /**
   * The '<em><b>Seven</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEVEN_VALUE
   * @generated
   * @ordered
   */
  SEVEN(6, "seven", "seven"),

  /**
   * The '<em><b>Eight</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EIGHT_VALUE
   * @generated
   * @ordered
   */
  EIGHT(7, "eight", "eight"),

  /**
   * The '<em><b>Nine</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NINE_VALUE
   * @generated
   * @ordered
   */
  NINE(8, "nine", "nine"),

  /**
   * The '<em><b>Ten</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEN_VALUE
   * @generated
   * @ordered
   */
  TEN(9, "ten", "ten"),

  /**
   * The '<em><b>Eleven</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELEVEN_VALUE
   * @generated
   * @ordered
   */
  ELEVEN(10, "eleven", "eleven");

  /**
   * The '<em><b>One</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONE
   * @model name="one"
   * @generated
   * @ordered
   */
  public static final int ONE_VALUE = 0;

  /**
   * The '<em><b>Two</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TWO
   * @model name="two"
   * @generated
   * @ordered
   */
  public static final int TWO_VALUE = 1;

  /**
   * The '<em><b>Three</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THREE
   * @model name="three"
   * @generated
   * @ordered
   */
  public static final int THREE_VALUE = 2;

  /**
   * The '<em><b>Four</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FOUR
   * @model name="four"
   * @generated
   * @ordered
   */
  public static final int FOUR_VALUE = 3;

  /**
   * The '<em><b>Five</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIVE
   * @model name="five"
   * @generated
   * @ordered
   */
  public static final int FIVE_VALUE = 4;

  /**
   * The '<em><b>Six</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SIX
   * @model name="six"
   * @generated
   * @ordered
   */
  public static final int SIX_VALUE = 5;

  /**
   * The '<em><b>Seven</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEVEN
   * @model name="seven"
   * @generated
   * @ordered
   */
  public static final int SEVEN_VALUE = 6;

  /**
   * The '<em><b>Eight</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EIGHT
   * @model name="eight"
   * @generated
   * @ordered
   */
  public static final int EIGHT_VALUE = 7;

  /**
   * The '<em><b>Nine</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NINE
   * @model name="nine"
   * @generated
   * @ordered
   */
  public static final int NINE_VALUE = 8;

  /**
   * The '<em><b>Ten</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TEN
   * @model name="ten"
   * @generated
   * @ordered
   */
  public static final int TEN_VALUE = 9;

  /**
   * The '<em><b>Eleven</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELEVEN
   * @model name="eleven"
   * @generated
   * @ordered
   */
  public static final int ELEVEN_VALUE = 10;

  /**
   * An array of all the '<em><b>Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Level[] VALUES_ARRAY =
    new Level[]
    {
      ONE,
      TWO,
      THREE,
      FOUR,
      FIVE,
      SIX,
      SEVEN,
      EIGHT,
      NINE,
      TEN,
      ELEVEN,
    };

  /**
   * A public read-only list of all the '<em><b>Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Level> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Level result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Level result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level get(int value)
  {
    switch (value)
    {
      case ONE_VALUE: return ONE;
      case TWO_VALUE: return TWO;
      case THREE_VALUE: return THREE;
      case FOUR_VALUE: return FOUR;
      case FIVE_VALUE: return FIVE;
      case SIX_VALUE: return SIX;
      case SEVEN_VALUE: return SEVEN;
      case EIGHT_VALUE: return EIGHT;
      case NINE_VALUE: return NINE;
      case TEN_VALUE: return TEN;
      case ELEVEN_VALUE: return ELEVEN;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Level(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Level
