/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.g2048;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level Define Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getLevel <em>Level</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getLevelDefineStatement()
 * @model
 * @generated
 */
public interface LevelDefineStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.languages.g2048.g2048.Level}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.Level
   * @see #setLevel(Level)
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getLevelDefineStatement_Level()
   * @model
   * @generated
   */
  Level getLevel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see uk.ac.kcl.inf.languages.g2048.g2048.Level
   * @see #getLevel()
   * @generated
   */
  void setLevel(Level value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' attribute.
   * @see #setElement(String)
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getLevelDefineStatement_Element()
   * @model
   * @generated
   */
  String getElement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.g2048.g2048.LevelDefineStatement#getElement <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' attribute.
   * @see #getElement()
   * @generated
   */
  void setElement(String value);

} // LevelDefineStatement
