/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.g2048;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Size Define Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getSizeDefineStatement()
 * @model
 * @generated
 */
public interface SizeDefineStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getSizeDefineStatement_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.g2048.g2048.SizeDefineStatement#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // SizeDefineStatement
