/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.g2048;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title Define Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement#getTitle <em>Title</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getTitleDefineStatement()
 * @model
 * @generated
 */
public interface TitleDefineStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see uk.ac.kcl.inf.languages.g2048.g2048.G2048Package#getTitleDefineStatement_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.g2048.g2048.TitleDefineStatement#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

} // TitleDefineStatement
