/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.languages.g2048.G2048RuntimeModule;
import uk.ac.kcl.inf.languages.g2048.G2048StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class G2048IdeSetup extends G2048StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new G2048RuntimeModule(), new G2048IdeModule()));
	}
	
}
