/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.languages.g2048.ide.contentassist.antlr.internal.InternalG2048Parser;
import uk.ac.kcl.inf.languages.g2048.services.G2048GrammarAccess;

public class G2048Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(G2048GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, G2048GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getLevelAccess().getAlternatives(), "rule__Level__Alternatives");
			builder.put(grammarAccess.getTitleDefineStatementAccess().getGroup(), "rule__TitleDefineStatement__Group__0");
			builder.put(grammarAccess.getSizeDefineStatementAccess().getGroup(), "rule__SizeDefineStatement__Group__0");
			builder.put(grammarAccess.getLevelDefineStatementAccess().getGroup(), "rule__LevelDefineStatement__Group__0");
			builder.put(grammarAccess.getG2048ProgramAccess().getStatementsAssignment(), "rule__G2048Program__StatementsAssignment");
			builder.put(grammarAccess.getTitleDefineStatementAccess().getTitleAssignment_1(), "rule__TitleDefineStatement__TitleAssignment_1");
			builder.put(grammarAccess.getSizeDefineStatementAccess().getSizeAssignment_1(), "rule__SizeDefineStatement__SizeAssignment_1");
			builder.put(grammarAccess.getLevelDefineStatementAccess().getLevelAssignment_1(), "rule__LevelDefineStatement__LevelAssignment_1");
			builder.put(grammarAccess.getLevelDefineStatementAccess().getElementAssignment_3(), "rule__LevelDefineStatement__ElementAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private G2048GrammarAccess grammarAccess;

	@Override
	protected InternalG2048Parser createParser() {
		InternalG2048Parser result = new InternalG2048Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public G2048GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(G2048GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
