/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class G2048UiModule extends AbstractG2048UiModule {

	public G2048UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
