/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class G2048ScopeProvider extends AbstractG2048ScopeProvider {

}
