/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractG2048ScopeProvider extends DelegatingScopeProvider {
}
