/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class G2048StandaloneSetup extends G2048StandaloneSetupGenerated {

	public static void doSetup() {
		new G2048StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
