/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.languages.g2048;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class G2048RuntimeModule extends AbstractG2048RuntimeModule {
}
